# Generated by Django 4.2.7 on 2023-11-08 09:50

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentAdding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID вещи')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sizes', models.CharField(default='36 37 38 39 40 41 42 43 44 45', max_length=50, verbose_name='Размеры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to=main.models.user_directory_path, verbose_name='Главное изображение')),
                ('second_image', models.ImageField(upload_to=main.models.user_directory_path, verbose_name='Втророе изображение')),
                ('third_image', models.ImageField(upload_to=main.models.user_directory_path, verbose_name='Третье изображение')),
                ('date', models.DateField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Добавление ассортимента',
                'verbose_name_plural': 'Добавление ассортимента',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('status', models.CharField(choices=[('Decorated', 'Оформлен'), ('Sent', 'Отправлен'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен'), ('Refund', 'Возврат')], max_length=10, verbose_name='Статус заказа')),
                ('items', models.IntegerField(verbose_name='ID заказанных вещей')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('adres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('post_index', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'.", regex='\\+7\\s?[\\(]{0,1}9[0-9]{2}[\\)]{0,1}\\s?\\d{3}[-]{0,1}\\d{2}[-]{0,1}\\d{2}')], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('start_date', models.DateField(verbose_name='Дата оформления заказа')),
                ('end_date', models.DateField(verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
