# Generated by Django 4.2.7 on 2023-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('sizes', models.IntegerField(default=[36, 37, 38, 39, 40, 41, 42, 43, 44, 45], verbose_name='Размеры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='static/main/images_new/', verbose_name='Главное изображение')),
                ('second_image', models.ImageField(upload_to='static/main/images_new/', verbose_name='Втророе изображение')),
                ('third_image', models.ImageField(upload_to='static/main/images_new/', verbose_name='Третье изображение')),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
            ],
        ),
    ]
