# Generated by Django 4.2.7 on 2023-11-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='second_name',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(default='OnlineCard', max_length=30, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(max_length=100, verbose_name='ID заказанных вещей'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
    ]
