# Generated by Django 4.2.7 on 2023-11-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assortment',
            new_name='AssortmentAdding',
        ),
        migrations.AlterModelOptions(
            name='assortmentadding',
            options={'verbose_name': 'Добавление ассортимента'},
        ),
    ]
