# Generated by Django 4.2.7 on 2023-11-09 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_second_name_orders_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 9, 12, 55, 2, 396294, tzinfo=datetime.timezone.utc), verbose_name='Дата оформления заказа'),
        ),
    ]
