# Generated by Django 4.2.7 on 2023-11-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_assortment_assortmentadding_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortmentadding',
            options={'verbose_name': 'Добавление ассортимента', 'verbose_name_plural': 'Добавление ассортимента'},
        ),
    ]
