# Generated by Django 4.2.7 on 2023-11-09 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_orders_end_date_alter_orders_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оформления заказа'),
        ),
    ]
