# Generated by Django 4.2.7 on 2023-11-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_assortmentadding_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortmentadding',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='assortmentadding',
            name='date',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
    ]
