# Generated by Django 4.2.7 on 2023-11-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orders_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID обращения')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('contact_description', models.TextField(verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Оформлен', 'Оформлен'), ('Отправлен', 'Отправлен'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен'), ('Возврат', 'Возврат')], default='Оформлен', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
