# Generated by Django 4.2.7 on 2023-11-13 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactus_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оформления заказа'),
        ),
    ]
