# Generated by Django 4.2.7 on 2023-11-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_assortmentadding_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentadding',
            name='main_image',
            field=models.ImageField(upload_to='static/main/images_new/assortment/None', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='assortmentadding',
            name='second_image',
            field=models.ImageField(upload_to='static/main/images_new/assortment/', verbose_name='Втророе изображение'),
        ),
        migrations.AlterField(
            model_name='assortmentadding',
            name='third_image',
            field=models.ImageField(upload_to='static/main/images_new/assortment/', verbose_name='Третье изображение'),
        ),
    ]
