# Generated by Django 4.2.7 on 2023-11-13 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactus_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата обращения'),
        ),
    ]
