# Generated by Django 4.2.7 on 2023-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_assortmentadding_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заказа')),
                ('status', models.CharField(choices=[('Decorated', 'Оформлен'), ('Sent', 'Отправлен'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен'), ('Refund', 'Возврат')], max_length=10, verbose_name='Статус заказа')),
                ('items', models.IntegerField(verbose_name='ID заказанных вещей')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('adres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('post_index', models.CharField(max_length=10, verbose_name='Почтовый индекс')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('start_date', models.DateField(verbose_name='Дата оформления заказа')),
                ('end_date', models.DateField(verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='assortmentadding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID вещи'),
        ),
        migrations.AlterField(
            model_name='assortmentadding',
            name='main_image',
            field=models.ImageField(upload_to='static/main/images_new/assortment/', verbose_name='Главное изображение'),
        ),
    ]
