# Generated by Django 4.2.7 on 2023-11-13 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contactus_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentadding',
            name='date',
            field=models.DateTimeField(verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оформления заказа'),
        ),
    ]
