# Generated by Django 4.2.7 on 2023-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_assortmentadding_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='refound_description',
            field=models.TextField(blank=True, null=True, verbose_name='Причина возврата'),
        ),
    ]
