# Generated by Django 4.2.7 on 2023-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orders_refound_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
    ]
