# Generated by Django 4.2.7 on 2023-11-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_orders_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
