# Generated by Django 4.2.7 on 2023-11-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_assortmentadding_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentadding',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
