# Generated by Django 4.2.7 on 2023-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_lastname_orders_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentadding',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID вещи'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID обращения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID заказа'),
        ),
    ]
