# Generated by Django 4.2.7 on 2023-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_assortmentadding_id_alter_contactus_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='refound_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID для оформления возврата'),
        ),
    ]
