# Generated by Django 4.2.7 on 2023-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orders_refound_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentadding',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID товара'),
        ),
    ]
