# Generated by Django 4.2.7 on 2023-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orders_final_price_alter_orders_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Оформлен', 'Оформлен'), ('Отправлен', 'Отправлен'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен'), ('Возврат', 'Возврат')], default='Оформлен', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
