# Generated by Django 4.2.7 on 2023-11-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_orders_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortmentadding',
            options={'verbose_name': 'Ассортимент', 'verbose_name_plural': 'Ассортимент'},
        ),
    ]
