# Generated by Django 4.2.7 on 2023-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID товара'),
        ),
    ]
