# Generated by Django 4.2.7 on 2023-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_cart_item_cart_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='assortmentadding',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
