# Generated by Django 4.2.7 on 2023-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cart_name_alter_assortmentadding_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Изображение'),
        ),
    ]
