# Generated by Django 4.2.7 on 2023-11-19 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortmentadding',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
