# Generated by Django 4.2.7 on 2023-11-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_assortmentadding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.AddField(
            model_name='orders',
            name='items_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID заказанных вещей'),
        ),
        migrations.AddField(
            model_name='orders',
            name='items_names',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Наименования заказанных вещей'),
        ),
    ]
