# Generated by Django 4.2.7 on 2023-11-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_orders_items_orders_items_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assortmentadding',
            old_name='date',
            new_name='add_date',
        ),
        migrations.AddField(
            model_name='assortmentadding',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
