# Generated by Django 5.0.3 on 2024-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_date_assortmentadding_add_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('status', models.CharField(default='False', max_length=10, verbose_name='Статус входа')),
                ('items_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID вещей в корзине')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
    ]
