# Generated by Django 5.0.3 on 2024-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус входа'),
        ),
    ]
