# Generated by Django 5.0.6 on 2024-05-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_users_options_remove_users_items_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
    ]
